apiVersion: v1

kind: Service

metadata:
  name: orchestrator-agent-service

spec:

  selector:
    app: orchestrator-agent

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: ClusterIP